meta:
  env: "dev"
  version: "0.0.1"
  squad: "infra"

image:
  repository: zendesk/maxwell
  tag: v1.25.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  class: nginx
  annotations: {}
  hosts:
    - host: maxwell.local
      paths: ["/"]
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configMap:
  enabled: true

  annotations: {}

  subPath: ""

  readOnly: true

  data:
    mw_host: "myql-po-maxwell.mysql.database.azure.com"
    mw_user: "maxwell"
    mw_password: "Xencia@12345"
    mw_producer: "rabbitmq"
    mw_rabbitmq_host: ".rabbitmq-headless.utilities.svc.cluster.local"
    mw_rabbitmq_port: "5672"
    mw_rabbitmq_user: "user"
    mw_rabbitmq_pass: "61WpMyqt8y6p52UI"
    mw_rabbitmq_virtual_host: "/"
    mw_rabbitmq_handshake_timeout: "20000"
    
