apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maxwell.fullname" . }}
  labels:
    {{- include "maxwell.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maxwell.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maxwell.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "maxwell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      ## Uncomment for minikube and access to host kafka
      ## change `ip` with your host ip, ref : https://minikube.sigs.k8s.io/docs/tasks/accessing-host-resources/
      # hostAliases:
      # - ip: "192.168.64.1"
      #   hostnames:
      #   - "host.docker.internal"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "image.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - bin/maxwell
          args:
          - --env_config_prefix=mw_
          envFrom:
          - configMapRef:
              name: {{ template "maxwell.fullname" . }}-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
